#!/bin/bash
#Created by Jenner.luo(Zhennan.luo)
set -e

docker_run_registry_in_local(){
    local host_dir=${1:-$(pwd)/registry}
    local container_dir=${2:-/var/lib/registry}
    local container_name=${3:-google-mirror-registry}
    local registry_img=${4:-registry.2.7.tar.gz}
    docker load -i $registry_img
    docker rm -f $container_name || echo "No $container_name exist"
    docker run -d -v ${host_dir}:${container_dir} -p 4000:5000 --restart=always --name $container_name registry:2.7
}

docker_run_registry_in_local
